USE sisi_test;

CREATE TABLE POSITION (
    POSITION_ID int AUTO_INCREMENT,
    POSITION_NAME varchar(100) NOT NULL,
    DESCRIPTION varchar(300),
    PRIMARY KEY (POSITION_ID)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID int AUTO_INCREMENT,
    ID_USER varchar(30) NULL,
    POSITION_ID int NOT NULL,
    EMPLOYEE_NUMBER varchar(30) NOT NULL,
    NATIONAL_ID varchar(30),
    EMPLOYEE_NAME varchar(100) NOT NULL,
    EMAIL varchar(200),
    PHONE varchar(30),
    ADDRESS varchar(300),
    JOIN_DATE date,
    BASIC_SALARY decimal(15,2),
    EMPLOYEE_STATUS varchar(30),
    PRIMARY KEY (EMPLOYEE_ID),
    UNIQUE (ID_USER),
    UNIQUE (EMPLOYEE_NUMBER),
    UNIQUE (NATIONAL_ID),
    FOREIGN KEY (ID_USER) REFERENCES `USER` (ID_USER),
    FOREIGN KEY (POSITION_ID) REFERENCES POSITION (POSITION_ID)
);

CREATE TABLE ATTENDANCE (
    ATTENDANCE_ID int AUTO_INCREMENT,
    EMPLOYEE_ID int NOT NULL,
    ATTENDANCE_DATE date NOT NULL,
    CHECK_IN time,
    CHECK_OUT time,
    ATTENDANCE_STATUS varchar(30),
    DESCRIPTION varchar(300),
    PRIMARY KEY (ATTENDANCE_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
);

CREATE TABLE LEAVE_REQUEST (
    LEAVE_ID int AUTO_INCREMENT,
    EMPLOYEE_ID int NOT NULL,
    LEAVE_TYPE varchar(30),
    START_DATE date,
    END_DATE date,
    REASON varchar(300),
    STATUS varchar(30),
    APPROVED_BY varchar(30) NULL,
    PRIMARY KEY (LEAVE_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID),
    FOREIGN KEY (APPROVED_BY) REFERENCES `USER` (ID_USER)
);

CREATE TABLE BUSINESS_TRIP (
    BUSINESS_TRIP_ID int AUTO_INCREMENT,
    EMPLOYEE_ID int NOT NULL,
    SPPD_NUMBER varchar(50),
    DEPARTURE_DATE date,
    RETURN_DATE date,
    DESTINATION varchar(200),
    PURPOSE varchar(300),
    TRANSPORTATION varchar(100),
    COST decimal(15,2),
    STATUS varchar(30),
    PRIMARY KEY (BUSINESS_TRIP_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
);

CREATE TABLE DEDUCTION_TYPE (
    DEDUCTION_TYPE_ID int AUTO_INCREMENT,
    DEDUCTION_NAME varchar(100) NOT NULL,
    DESCRIPTION varchar(300),
    PRIMARY KEY (DEDUCTION_TYPE_ID)
);

CREATE TABLE PAYROLL (
    PAYROLL_ID int AUTO_INCREMENT,
    EMPLOYEE_ID int NOT NULL,
    `MONTH` int NOT NULL,
    `YEAR` int NOT NULL,
    BASIC_SALARY decimal(15,2),
    TOTAL_DEDUCTION decimal(15,2),
    NET_SALARY decimal(15,2),
    PROCESS_DATE date,
    STATUS varchar(30),
    PRIMARY KEY (PAYROLL_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
);

CREATE TABLE PAYROLL_DEDUCTION (
    PAYROLL_DEDUCTION_ID int AUTO_INCREMENT,
    PAYROLL_ID int NOT NULL,
    DEDUCTION_TYPE_ID int NOT NULL,
    AMOUNT decimal(15,2),
    PRIMARY KEY (PAYROLL_DEDUCTION_ID),
    FOREIGN KEY (PAYROLL_ID) REFERENCES PAYROLL (PAYROLL_ID),
    FOREIGN KEY (DEDUCTION_TYPE_ID) REFERENCES DEDUCTION_TYPE (DEDUCTION_TYPE_ID)
);